#!/bin/bash
# Crude install script for nginx-unit and a python3 module to /opt/unit.
# This is the standard configure, make, make install flow.
#
# Note that if this fails, it leaves around the temporary build directory
# for you to inspect (and clean up).
set -eo pipefail

version=$1

[ "$version" ] || {
  echo >&2 "usage: $0 VERSION"
  echo >&2 "  - i.e. $0 1.22.0"
  echo >&2 "  - see https://github.com/nginx/unit/releases for versions"
  exit 1
}

[ -e "/opt/unit" ] && {
  echo >&2 "unit install already exists"
  exit 1
}


curl -L "https://github.com/nginx/unit/archive/$version.tar.gz" | tar -xzf -
cd "unit-$version"
./configure --openssl --prefix=/opt/unit
./configure python --config="python3-config"
make
sudo make install
cd ..
rm -rf "unit-$version"  # cleanup temp directory

sudo /opt/unit/sbin/unitd  # start unitd
