#!/bin/bash
# This calls certbot to get a TLS certificate for your domain
# and sets up auto-renewal with certbot's hooks
set -eo pipefail

domain=$1
[ "$domain" ] || {
  echo >&2 "usage: $0 DOMAIN"
  echo >&2 "  - i.e. $0 my.website.com"
  exit 1
}
[ $EUID = 0 ] || {
  echo >&2 "this script must be run as root"
  exit 1
}

# initial certificate
certbot certonly -d "$domain" --standalone

# automate the cert renewal process
function make_script {
  path=$1; shift
  ( for line in "$@"; do echo "$line"; done ) > "$path" && chmod +x "$path"
}
make_script /etc/letsencrypt/renewal-hooks/pre/"$domain" \
  "/opt/unit/sbin/unit-admin suspend-listener '*:80'"

make_script /etc/letsencrypt/renewal-hooks/post/"$domain" \
  "/opt/unit/sbin/unit-admin restore-listener '*:80'"

make_script /etc/letsencrypt/renewal-hooks/deploy/"$domain" \
  "/opt/unit/sbin/unit-admin load-cert '$domain'" \
  "/opt/unit/sbin/unit-admin use-latest-cert '$domain' '*:443'" \
  "/opt/unit/sbin/unit-admin delete-old-certs '$domain'"

make_script /etc/cron.weekly/certbot-renew "certbot renew >>/opt/unit/unit.cert-renewal.log 2>&1"
