#!/bin/bash

# Create a python3 virtual environment and an example FastAPI app
# and sudo jam-it-all-in-/web

set -exo pipefail

sudo mkdir -p -m 777 /web
sudo -u nobody sh -c "python3 -m venv /web/venv; source /web/venv/bin/activate; pip install fastapi"
sudo cp -r unit-example /web/
sudo chown -R nobody: /web
sudo chmod 555 /web

sudo curl -X PUT --data-binary '{
  "listeners": {
    "*:80": {
      "pass": "applications/example"
    },
    "*:443": {
      "pass": "applications/example",
      "tls": {"certificate": "my-certificate"}
    }
  },
  "applications": {
      "example": {
          "type": "python",
          "home": "/opt/example-venv",
          "path": "/opt/unit-example/",
          "module": "redirector",
          "callable": "app",
          "processes": 2,
      }
  }
}' --unix-socket /opt/unit/control.unit.sock localhost/config
