#!/bin/bash
# This creates a systemd init script for unit, and
# then "enable"s it (causes it to run on startup)

[ $EUID = 0 ] || {
  echo >&2 "this script must be run as root"
  exit 1
}

echo '
[Unit]
Description=NGINX Unit
After=network-online.target

[Service]
Type=forking
PIDFile=/opt/unit/unit.pid
ExecStart=/opt/unit/sbin/unitd
Restart=always

[Install]
WantedBy=multi-user.target
' | tee /etc/systemd/system/unit.service >/dev/null

systemctl enable unit
systemctl start unit

