#!/bin/bash
# Super crude creation of an example in /web

set -eo pipefail

domain=$1
[ "$domain" ] || {
  echo >&2 "usage: $0 DOMAIN"
  echo >&2 "  - i.e. $0 my.website.com"
  exit 1
}
[ $EUID = 0 ] || {
  echo >&2 "this script must be run as root"
  exit 1
}

mkdir -p -m 777 /web/example
sudo -u nobody bash -c "python3 -m venv /web/example/venv; source /web/example/venv/bin/activate; pip install fastapi"
cp tools/example.py /web/example/example.py
chown -R nobody: /web/example
chmod 555 /web/example

curl -X PUT --data-binary '{
  "listeners": {
    "*:80": {
      "pass": "applications/example"
    },
    "*:443": {
      "pass": "applications/example",
    }
  },
  "applications": {
      "example": {
          "type": "python",
          "home": "/web/example/venv",
          "path": "/web/example",
          "module": "example",
          "callable": "app",
          "processes": 2,
      }
  }
}' --unix-socket /opt/unit/control.unit.sock localhost/config

/opt/unit/sbin/unit-admin use-latest-cert "$domain" '*:443'
