#!/bin/bash
# This calls certbot to get a TLS certificate for your domain
# and sets up auto-renewal with certbot's hooks
set -eo PIPEFAIL

domain=$1
[ "$domain" ] || {
  echo >&2 "usage: $0 DOMAIN"
  echo >&2 "  - i.e. $0 my.website.com"
  exit 1
}
[ $EUID = 0 ] || {
  echo >&2 "this script must be run as root"
  exit 1
}


certbot certonly -d "$domain" --standalone

# automate the cert renewal process
function make_script {
  path=$1; shift
  ( for line in "$@"; do echo "$line"; done ) > "$path" && chmod +x "$path"
}
cp tools/admin.py /opt/unit/sbin/admin.py
make_script /etc/letsencrypt/renewal-hooks/pre/"$domain" "/opt/unit/sbin/admin.py suspend-listener '*:80'"
make_script /etc/letsencrypt/renewal-hooks/post/"$domain" "/opt/unit/sbin/admin.py restore-listener '*:80'"
make_script /etc/letsencrypt/renewal-hooks/deploy/"$domain" \
  "/opt/unit/sbin/admin.py load-cert '$domain'" \
  "/opt/unit/sbin/admin.py use-latest-cert '$domain' '*:443'" \
  "/opt/unit/sbin/admin.py delete-old-certs '$domain'"
make_script /etc/cron.weekly/certbot-renew "certbot renew"
