#!/bin/bash
# Pack up some files for install on the server
# This is pretty direct...don't do anything funny with paths and special characters!
set -eo pipefail

[ "$3" ] || {
  echo >&2 "usage: $0 ssh_host[:port] source_dir dest_dir"
  echo >&2 "  i.e. $0 raspi-ip-address ~/dev/my-react-app/build /web/my-app/static"
  exit 1
}

host=$1
src=$2
dest=$3

tar -C "$src" -cf - . | ssh "$host" "sudo -u nobody sh -c 'rm -rf \"$dest\"; mkdir \"$dest\"; tar -C \"$dest\" -xf -'"

echo "done!"
