#!/bin/bash
# open the current nginx-unit config (or sub-config if path is specified)
# in vim for editing, and if vim exits successfully then post the result
# back to nginx-unit.
set -e

[ $EUID = 0 ] || {
  echo >&2 "this script must be run as root"
  exit 1
}

curl='curl -sS --unix-socket /opt/unit/control.unit.sock'
tmp=~/.tmp-unit-config.json
path=localhost/config/$1

$curl $path >$tmp && vim $tmp && $curl -X PUT --data-binary @$tmp $path
